on:
  push:
    branches:
      - main

jobs:
  update_beta:
    name: Update Website
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd tolgchu
            git pull
            npm install
            npm run build
            pm2 reload 17
